<?php
/**
 * @var Taxonomy\Api\Representation\TaxonomyTermRepresentation $taxonomyTerm
 */

$this->headScript()->appendFile($this->assetUrl('js/taxonomy-linked-resources.js'));
?>

<section class="section taxonomy-linked-resources" data-url="<?= $this->url('site/taxonomy-term-id', ['action' => 'linked-resources'], [], true) ?>">

    <?php if ($taxonomyTerm->linkedResourcesCount() > 0): ?>
        <div class="taxonomy-linked-resources__resources__direct"></div>
        <div class="taxonomy-linked-resources__resources__descendants"></div>
    <?php else: ?>
        <div class="no-resources">
            <p><?php echo $this->translate('No resources link to this taxonomy term or its descendants.'); ?></p>
        </div>
    <?php endif; ?>
</section>