<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'taxonomy-terms show');
$this->headLink()->appendStylesheet($this->assetUrl('css/site/taxonomy.css', 'Taxonomy'));
?>

<?php echo $this->pageTitle($taxonomyTerm->displayTitle()); ?>

<?php $this->trigger('view.show.before'); ?>

<div id="taxonomy-term-metadata" class="section">
    <?php echo $taxonomyTerm->displayValues(); ?>
</div>

<?= $this->partial('taxonomy/site/taxonomy-term/linked-resources', ['taxonomyTerm' => $taxonomyTerm]) ?>

<?php $this->trigger('view.show.after'); ?>