<?php
use Laminas\Form\Element\Select;

// Set up pagination.
$pagination = $this->pagination(null, $totalCount, $page, $perPage);
$fragment = 'resources-linked';
$pagination->setFragment($fragment);
$pagecount = 0;

// Set up locale.
$valueLang = null;
if ($this->status()->isSiteRequest()) {
    $lang = $this->lang();
    $filterLocale = (bool) $this->siteSetting('filter_locale_values');
    $valueLang = $filterLocale ? [$lang, ''] : null;
}

// Set up resource property select.
$labelMap = [
    'items' => 'Items', // @translate
    'item_sets' => 'Item sets', // @translate
    'media' => 'Media', // @translate
];
$resourcePropertiesSelect = new Select('resource_property');
$resourcePropertiesSelect->setValue($resourceProperty);
$resourcePropertiesSelect->setAttributes([
    'id' => 'resource-property-select',
    'data-url' => $this->url(null, [], true),
    'data-fragment' => $fragment,
]);
$valueOptions = [];
foreach ($resourcePropertiesAll as $type => $resourceProperties) {
    if (!$resourceProperties) {
        continue;
    }
    $valueOptions[$type] = [
        'label' => $labelMap[$type],
        'options' => [sprintf('%s:', $type) => sprintf('%s: All', $labelMap[$type])],
    ];
    foreach ($resourceProperties as $resourceProperty) {
        $label = $resourceProperty['label_is_translatable']
            ? $this->translate($resourceProperty['label'])
            : $resourceProperty['label'];
        $valueOptions[$type]['options'][] = [
            'value' => $resourceProperty['compound_id'],
            'label' => sprintf('%s: %s', $labelMap[$type], $label),
            'attributes' => [
                'title' => $resourceProperty['term'],
            ],
        ];
    }
}
$resourcePropertiesSelect->setValueOptions($valueOptions);
?>
<div id="linked-resources">

<?php foreach ($subjectValues as $values): ?>
<?php if ($values[0]['property_label'] != 'has narrower' && $values[0]['property_label'] != 'has top concept' && $values[0]['property_label'] != 'has broader' && $values[0]['property_label'] != 'is in scheme'):
$pagecount = 1;
$caption = sprintf(
    $this->translate('%s with "%s: %s"'),
    $this->translate($labelMap[$resourceType]),
    $values[0]['property_alternate_label'] ?? $this->translate($values[0]['property_label']),
    $objectResource->displayTitle()
);
?>
    <caption class="linked-resource-property"><?php echo $this->escapeHtml($caption); ?></caption>
    <ul>
        <?php foreach ($values as $value): ?>
        <li class="linked-resource">
            <?php echo $value['val']->resource()->linkPretty('square', null, null, ['target' => '_blank'], $valueLang); ?>
        </li>
        <?php endforeach; ?>
</ul>
<?php endif; ?>
<?php endforeach; ?>
<?php echo ($totalCount > $perPage && $pagecount) ? '<div class="linked-footer">' . $pagination . '</div>' : ''; ?>
</div>