<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$labelInfo = $this->fallbackSetting('property_label_information', ['site', 'global'], 'none');
$showLocale = (bool) $this->fallbackSetting('show_locale_label', ['site'], true);
$filterLocale = (bool) $this->fallbackSetting('filter_locale_values', ['site'], false);
$lang = $this->lang();

$filterLocaleCallback = function ($value) use ($lang) {
    $valueLang = $value->lang();
    return $valueLang == '' || strcasecmp($valueLang, $lang) === 0;
};
?>
<?php if (count($values) > 0): ?>
<?php
foreach ($values as $term => $propertyData):
    $propertyValues = $propertyData['values'];
    if ($filterLocale) {
        $propertyValues = array_filter($propertyValues, $filterLocaleCallback);
    }
    if (!$propertyValues) {
        continue;
    }
    $property = $propertyData['property'];
    $propertyLabel = $propertyData['alternate_label'] ?: $translate($property->label());
    if ('term' === $labelInfo) {
        $propertyTerm = $property->term();
    } elseif ('vocab' === $labelInfo) {
        $propertyTerm = $property->vocabulary()->label();
    } else {   
        $propertyTerm = null;
    }
    $parts = [];
?>
    <span class="annotation-prop">
        <?php if ($propertyLabel == 'sidor'):
            $label = '( s. ';
            elseif ($propertyLabel == 'pages'):
            $label = '( p. ';
            elseif ($property->label() == 'Description'):
            $label = '';
            else:
            $label = $escape($propertyLabel);
            endif;
            echo $label;
        ?>
        <?php if ($propertyTerm !== null): ?>
        <span class="field-term">(<?php echo $escape($propertyTerm); ?>)</span>
        <?php endif; ?>
        <?php foreach ($propertyValues as $value): ?>
        <?php
        ob_start();
        $valueType = $value->type();
        $valueLang = $value->lang();
        $class = ['value'];
        if ('resource' == $valueType || strpos($valueType,'resource') !== false) {
            $class[] = 'resource';  
            $class[] = $escape($value->valueResource()->resourceName());
        } elseif ('uri' == $valueType) {
            $class[] = 'uri';
        } else {  
            $class[] = $escape(str_replace(['_', ':'], '-',$valueType));
        }
        ?>
        <?php if ($showLocale && $valueLang): ?>
            <span class="language"><?php echo $valueLang; ?></span>
        <?php endif; ?>
            <span class="value-content"><?php echo $filterLocale ? $value->asHtml($lang) : $value->asHtml(); ?></span>
        <?php if(!$value->isPublic()): ?>
            <span class="o-icon-private" role="img" title="<?php echo $this->escapeHtml($translate('Private')); ?>" aria-label="<?php echo $this->escapeHtml($translate('Private')); ?>"></span>
         <?php endif; ?>
         <?php $this->trigger('view.show.value', ['value' => $value]); ?>
        <?php $parts[] = trim(ob_get_clean()); ?>
        <?php endforeach; ?>
        <?php echo implode(', ', $parts); ?>
        <?php if ($property->label() == 'pages'): ?>
          <?php echo ')' ?>
        <?php endif; ?>
    </span>
<?php endforeach; ?>
<?php endif; ?>
