<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var \Omeka\Api\Representation\ItemRepresentation $item
 * @var string $type
 * @var array $options
 */
$this->headLink()->appendStylesheet($this->assetUrl('css/jstree.css', 'Omeka'));
$this->headScript()
    ->appendFile($this->assetUrl('vendor/jstree/jstree.min.js', 'Omeka'))
    ->appendFile($this->assetUrl('js/jstree-plugins.js', 'Omeka'))
    ->appendFile($this->assetUrl('js/jstree-init.js'));
?>

<div class="block-thesaurus">
    <?php if ($item): ?>
    <?= $this->thesaurus($item)->display($type, $options) ?>
    <?php endif; ?>
</div>