<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'taxonomies show');
?>

<?php echo $this->pageTitle($taxonomy->displayTitle()); ?>

<?php $this->trigger('view.show.before'); ?>

<div id="taxonomy-metadata" class="section">
    <?php echo $taxonomy->displayValues(); ?>
</div>

<div id="taxonomy-linked" class="section">
    <h2><?php echo $translate('Linked resources'); ?></h2>
    <?php
    $page = $this->params()->fromQuery('page', 1);
    $property = $this->params()->fromQuery('property');
    $subjectValues = $taxonomy->displaySubjectValuesCompat(['page' => $page, 'perPage' => 25]);
    ?>
    <?php if ($subjectValues): ?>
        <p><?php echo $translate('The following resources link to this taxonomy:'); ?></p>
        <?php echo $subjectValues; ?>
    <?php else: ?>
        <div class="no-resources">
            <p><?php echo $translate('No resources link to this taxonomy.'); ?></p>
        </div>
    <?php endif; ?>
</div>

<?php $this->trigger('view.show.after'); ?>