<?php
$options = [
    'page' => $this->params()->fromQuery('page', 1),
    'perPage' => 25,
    'resourceProperty' => $this->params()->fromQuery('resource_property'),
    'siteId' => null,
]; 
if ($this->siteSetting('exclude_resources_not_in_site')) {
    $options['siteId'] = $this->currentSite()->id();
}
$profiles = $this->setting('annotationprofiles_profiles', '[]');
$templateProfiles = $this->setting('annotationprofiles_template_profiles', '[]');

$template = $resource->resourceTemplate();
$templateId = $template ? $template->id() : null;

$profileKey = ($templateId !== null && isset($templateProfiles[$templateId])) ? $templateProfiles[$templateId] : null;
$profile    = ($profileKey !== null && isset($profiles[$profileKey])) ? $profiles[$profileKey] : null;

?>
<?php if ($resource->subjectValueTotalCount(null, null, $options['siteId'])):
      $docs = $this->relatedAnnotatedItems($resource, [
        'relation_property'     => $profile['relation_property'] ?? 'dcterms:subject',
        'annotation_properties' => $profile['annotation_properties'] ?? [],
        'resource_type'         => $profile['resource_type'] ?? 'items',
]);
if ($docs): ?>
<dl class="linked-resources">
    <dt><?php if ($profile["relation_property"] == "dcterms:isPartOf"):
    echo sprintf(
    $this->translate('"%s" is part of the following documents:'),
    $resource->displayTitle());
    else:
    echo sprintf(
    $this->translate('"%s" is mentioned in the following documents:'),
    $resource->displayTitle()
    );
    endif; ?></dt>
<?php foreach ($docs as $row):
    $doc   = $row['related'];
    $annotations = $row['annotations'];?>
    <dd><?php echo $this->hyperlink($doc->displayTitle(), $doc->url());?>
      <?php if ($annotations): ?><span>(p. <?php echo implode(",", $annotations["pages"]);?>)</span><?php endif; ?>
    </dd>
<?php endforeach; ?>
</dl>
 <?php else: ?>
    <?php echo $resource->displaySubjectValues($options); ?>
 <?php endif; ?>
<?php endif; ?>
